@startuml

title __DAOS's Class Diagram__\n

  namespace pl.edu.uj.ii.ionb.airportmanager.backend.daos {
    interface pl.edu.uj.ii.ionb.airportmanager.backend.daos.AirPlaneDB {
        {abstract} + createAirplane()
        {abstract} + getAirplane()
        {abstract} + getAllAirplanes()
        {abstract} + getAllAirplanesFlights()
        {abstract} + removeAirplane()
        {abstract} + updateAirplane()
    }
  }
  

  namespace pl.edu.uj.ii.ionb.airportmanager.backend.daos {
    interface pl.edu.uj.ii.ionb.airportmanager.backend.daos.DestinationDB {
        {abstract} + createDestination()
        {abstract} + getAllDestinations()
        {abstract} + getAllIncomingFlights()
        {abstract} + getAllOutcomingFlights()
        {abstract} + getDestination()
        {abstract} + removeDestination()
        {abstract} + updateDestination()
    }
  }
  

  namespace pl.edu.uj.ii.ionb.airportmanager.backend.daos {
    interface pl.edu.uj.ii.ionb.airportmanager.backend.daos.FlightDB {
        {abstract} + createFlight()
        {abstract} + getAllFlight()
        {abstract} + getFlight()
        {abstract} + removeFlight()
        {abstract} + updateFlight()
    }
  }
  

  namespace pl.edu.uj.ii.ionb.airportmanager.backend.daos {
    interface pl.edu.uj.ii.ionb.airportmanager.backend.daos.StewardDB {
        {abstract} + createSteward()
        {abstract} + getAllStewards()
        {abstract} + getAllStewardsFlights()
        {abstract} + getSteward()
        {abstract} + removeSteward()
        {abstract} + updateSteward()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
