@startuml

title __IMPL's Class Diagram__\n

  namespace pl.edu.uj.ii.ionb.airportmanager.backend.daos {
    namespace impl {
      class pl.edu.uj.ii.ionb.airportmanager.backend.daos.impl.AirPlaneDBimpl {
          - em : EntityManager
          + createAirplane()
          + getAirplane()
          + getAllAirplanes()
          + getAllAirplanesFlights()
          + removeAirplane()
          + updateAirplane()
      }
    }
  }
  

  namespace pl.edu.uj.ii.ionb.airportmanager.backend.daos {
    namespace impl {
      class pl.edu.uj.ii.ionb.airportmanager.backend.daos.impl.AirportDBException {
          + AirportDBException()
          + AirportDBException()
          + AirportDBException()
          + AirportDBException()
      }
    }
  }
  

  namespace pl.edu.uj.ii.ionb.airportmanager.backend.daos {
    namespace impl {
      class pl.edu.uj.ii.ionb.airportmanager.backend.daos.impl.DestinationDBimpl {
          - em : EntityManager
          + createDestination()
          + getAllDestinations()
          + getAllIncomingFlights()
          + getAllOutcomingFlights()
          + getDestination()
          + removeDestination()
          + updateDestination()
      }
    }
  }
  

  namespace pl.edu.uj.ii.ionb.airportmanager.backend.daos {
    namespace impl {
      class pl.edu.uj.ii.ionb.airportmanager.backend.daos.impl.FlightDBimpl {
          - em : EntityManager
          + createFlight()
          + getAllFlight()
          + getFlight()
          + removeFlight()
          + updateFlight()
      }
    }
  }
  

  namespace pl.edu.uj.ii.ionb.airportmanager.backend.daos {
    namespace impl {
      class pl.edu.uj.ii.ionb.airportmanager.backend.daos.impl.StewardDBimpl {
          - manager : EntityManager
          + createSteward()
          + getAllStewards()
          + getAllStewardsFlights()
          + getSteward()
          + removeSteward()
          + updateSteward()
      }
    }
  }
  

  pl.edu.uj.ii.ionb.airportmanager.backend.daos.impl.AirPlaneDBimpl .up.|> pl.edu.uj.ii.ionb.airportmanager.backend.daos.AirPlaneDB
  pl.edu.uj.ii.ionb.airportmanager.backend.daos.impl.AirportDBException -up-|> javax.persistence.PersistenceException
  pl.edu.uj.ii.ionb.airportmanager.backend.daos.impl.DestinationDBimpl .up.|> pl.edu.uj.ii.ionb.airportmanager.backend.daos.DestinationDB
  pl.edu.uj.ii.ionb.airportmanager.backend.daos.impl.FlightDBimpl .up.|> pl.edu.uj.ii.ionb.airportmanager.backend.daos.FlightDB
  pl.edu.uj.ii.ionb.airportmanager.backend.daos.impl.StewardDBimpl .up.|> pl.edu.uj.ii.ionb.airportmanager.backend.daos.StewardDB


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
